version: "3.9"
services:
  rts-1:
    build: ./rts
    depends_on:
      - redis
  rts-2:
    build: ./rts
    depends_on:
      - redis
  server:
    build: ./server
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
